### ISSUE TITLE
Freeze on start

### ISSUE THREAD

**Issue by squili** [Litleck/dm-typing-indicator#4]
On the latest version of canary, this plugin causes powercord to freeze on start. Doesn't cause a bootloop, but it does mean it freezes during the fade in so you can't use the app.

Info:
Canary 85548 (c81e78c)
Host 0.0.121
Linux 64-Bit (5.4.0-73-Generic)
Powercord v2 (111398d)

**Comment by Litleck** [comment]
> On the latest version of canary, this plugin causes powercord to freeze on start. Doesn't cause a bootloop, but it does mean it freezes during the fade in so you can't use the app.
> 
> Info:
> Canary 85548 (c81e78c)
> Host 0.0.121
> Linux 64-Bit (5.4.0-73-Generic)
> Powercord v2 (111398d)

Apologies for the late reply, but with the PR #6 it should help with performance issues if they're still present.
